name: Playwright Tests
# on:
#   push:
#     branches: [main, master]
#   pull_request:
#     branches: [main, master]

on:
  push:
    branches:
      - main
env:
  PNPM_VERSION: ${{ vars.PNPM_VERSION }}
  GITHUB_ID: ${{ secrets.X_GITHUB_ID }}
  GITHUB_SECRET: ${{ secrets.X_GITHUB_SECRET }}
  SECRET: ${{ secrets.SECRET }}
  NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
  RESEND_DOMAIN: ${{ vars.RESEND_DOMAIN }}
  NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
  SITE_NAME: ${{ vars.SITE_NAME }}
  SITE_URL: ${{ vars.SITE_URL }}
  TWITTER_CREATOR: ${{ vars.TWITTER_CREATOR }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 🔥 Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@${{ env.PNPM_VERSION}} --activate

      - name: 📦 Install Dependencies
        run: |
          pnpm install --no-frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: 💣 test:e2e
        run: pnpm test:e2e

      # - name: Run Playwright tests
      #   run: pnpm exec playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
